package com.karankumar.covid19stats;

// This should be kept in alphabetical order

// The country names should match https://api.covid19api.com/countries
// Exceptions include names that have parentheses or commas in them (this does not apply to Congo as there would be ambiguity)
public enum CountryName {
    AFGHANISTAN("Afghanistan"),
    ALA_ALAND_ISLANDS("ALA Aland Islands"),
    ALBANIA("Albania"),
    ALGERIA("Algeria"),
    AMERICAN_SAMOA("American Samoa"),
    ANDORRA("Andorra"),
    ANGOLA("Angola"),
    ANGUILLA("Anguilla"),
    ANTARCTICA("Antarctica"),
    ANTIGUA("Antigua and Barbuda"),
    ARGENTINA("Argentina"),
    ARMENIA("Armenia"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    ARUBA("Aruba"),
    AZERBAIJAN("Azerbaijan"),
    BAHAMAS("Bahamas"),
    BAHRAIN("Bahrain"),
    BANGLADESH("Bangladesh"),
    BARBADOS("Barbados"),
    BELARUS("Belarus"),
    BELGIUM("Belgium"),
    BELIZE("Belize"),
    BENIN("Benin"),
    BERMUDA("Bermuda"),
    BHUTAN("Bhutan"),
    BOLIVIA("Bolivia"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina"),
    BOTSWANA("Botswana"),
    BOUVET_ISLAND("Bouvet Island"),
    BRAZIL("Brazil"),
    BRITISH_INDIAN_OCEAN_TERRITORY("British Indian Ocean Territory"),
    BRITISH_VIRGIN_ISLANDS("British Virgin Islands"),
    BRUNEI_DARUSSALAM("Brunei Darussalam"),
    BULGARIA("Bulgaria"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),
    CAMBODIA("Cambodia"),
    CAMEROON("Cameroon"),
    CANADA("Canada"),
    CAPE_VERDE("Cape Verde"),
    CAYMAN_ISLANDS("Cayman Islands"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic"),
    CHAD("Chad"),
    CHILE("Chile"),
    CHINA("China"),
    CHRISTMAS_ISLAND("Christmas Island"),
    COCOS("Cosos (Keeling) Islands"),
    COOK_ISLANDS("Cook Islands"),
    COLUMBIA("Columbia"),
    COMOROS("Comoros"),
    CONGO_BRAZZAVILLE("Congo (Brazzaville)"),
    CONGO_KINSHASA("Congo (Kinshasa)"),
    COSTA_RICA("Costa Rica"),
    CÔTE_D_IVOIRE("Côte d'Ivoire"),
    CROATIA("Croatia"),
    CUBA("Cuba"),
    CYPRUS("CYPRUS"),
    CZECH_REPUBLIC("Czech Republic"),
    DENMARK("Denmark"),
    DJIBOUTI("Djibouti"),
    DOMINICA("Dominica"),
    DOMINICAN_REPUBLIC("Dominican Republic"),
    ECUADOR("Ecuador"),
    EGYPT("Egypt"),
    EL_SALVADOR("El Salvador"),
    EQUATORIAL_GUINEA("Equatorial Guinea"),
    ERITREA("Eritrea"),
    ESTONIA("Estonia"),
    ETHIOPIA("Ethiopia"),
    FALKLAND_ISLANDS("Falkland Islands (Malvinas)"),
    FAROE_ISLANDS("Faroe Islands"),
    FIJI("Fiji"),
    FINLAND("Finland"),
    FRANCE("France"),
    FRENCH_GUIANA("French Guiana"),
    FRENCH_POLYNESIA("French Polynesia"),
    FRENCH_SOUTHERN_TERRITORIES("French Southern Territories"),
    GABON("Gabon"),
    GAMBIA("Gambia"),
    GEORGIA("Georgia"),
    GERMANY("Germany"),
    GHANA("Ghana"),
    GIBRALTAR("Gibraltar"),
    GREECE("Greece"),
    GREENLAND("Greenland"),
    GRENADA("Grenada"),
    GUADELOUPE("Guadeloupe"),
    GUAM("Guam"),
    GUATEMALA("Guatemala"),
    GUERNSEY("Guernsey"),
    GUINEA("Guinea"),
    GUINEA_BISSAU("Guinea-Bissau"),
    GUYANA("GUYANA"),
    HAITI("Haiti"),
    HEARD_AND_MCDONALD_ISLANDS("Heard and Mcdonald Islands"),
    HOLY_SEE("Holy See (Vatican City State)"),
    HONDURAS("Honduras"),
    HONG_KONG("Hong Kong, SAR China"),
    HUNGARY("Hungary"),
    ICELAND("Iceland"),
    INDONESIA("Indonesia"),
    INDIA("India"),
    IRAQ("Iraq"),
    IRAN("Iran, Islamic Republic of"),
    IRELAND("Ireland"),
    ISLE_OF_MAN("Isle of Man"),
    ISRAEL("Israel"),
    ITALY("Italy"),
    JAMAICA("Jamaica"),
    JAPAN("Japan"),
    JERSEY("Jersey"),
    JORDAN("Jordan"),
    KAZAKHSTAN("Kazakhstan"),
    KENYA("Kenya"),
    KIRIBATI("Kiribati"),
    KUWAIT("Kuwait"),
    KYRGYZSTAN("Kyrgyzstan"),
    LAO_PDR("Lao PDR"),
    LATVIA("Latvia"),
    LEBANON("Lebanon"),
    LESOTHO("Lesotho"),
    LIBERIA("Liberia"),
    LIBYA("Libya"),
    LIECHTENSTEIN("Liechtenstein"),
    LITHUANIA("Lithuania"),
    LUXEMBOURG("Luxembourg"),
    MACAO("Macao, SAR China"),
    MACEDONIA("Macedonia, Republic of"),
    MADAGASCAR("Madagascar"),
    MALAWI("Malawi"),
    MALAYSIA("Malaysia"),
    MALDIVES("Maldives"),
    MALI("Mali"),
    MALTA("Malta"),
    MARSHALL_ISLANDS("Marshall Islands"),
    MARTINIQUE("Martinique"),
    MAURITANIA("Mauritania"),
    MAURITIUS("Mauritius"),
    MAYOTTE("Mayotte"),
    MEXICO("Mexico"),
    MICRONESIA("Micronesia, Federated States of"),
    MOLDOVA("Moldova"),
    MONACO("Monaco"),
    MONGOLIA("Mongolia"),
    MONTENEGRO("Montenegro"),
    MONTSERRAT("Montserrat"),
    MOROCCO("Morocco"),
    MOZAMBIQUE("Mozambique"),
    MYANMAR("MYANMAR"),
    NAMIBIA("Namibia"),
    NAURU("Nauru"),
    NEPAL("Nepal"),
    NETHERLANDS("Netherlands"),
    NETHERLANDS_ANTILLES("Netherlands Antilles"),
    NEW_CALEDONIA("New Caledonia"),
    NEW_ZEALAND("New Zealand"),
    NICARAGUA("Nicaragua"),
    NIGER("Niger"),
    NIGERIA("Nigeria"),
    NIUE("Niue"),
    NORFOLK_ISLAND("Norfolk Island"),
    NORTH_KOREA("North Korea"),
    NORTHERN_MARIANA_ISLANDS("Northern Marina Islands"),
    NORWAY("Norway"),
    OMAN("Oman"),
    PALAU("Palau"),
    PALESTINIAN_TERRITORY("Palestinian Territory"),
    PAKISTAN("Pakistan"),
    PANAMA("Panama"),
    PAPA_NEW_GUINEA("Papa New Guinea"),
    PARAGUAY("Paraguay"),
    PERU("Peru"),
    PHILIPPINES("Philippines"),
    PITCAIRN("Pitcairn"),
    POLAND("Poland"),
    PUERTO_RICO("Puerto Rico"),
    PORTUGAL("Portugal"),
    QATAR("Qatar"),
    REPUBLIC_OF_KOSOVO("Republic of Kosovo"),
    RUSSIAN_FEDERATION("Russian Federation"),
    RÉUNION("Réunion"),
    ROMANIA("Romania"),
    RWANDA("Rwanda"),
    SAINT_BARTHÉLEMY("Saint Barthélemy"),
    SAINT_HELENA("Saint Helena"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis"),
    SAINT_LUCIA("Saint Lucia"),
    SAINT_MARTIN("Saint Martin (French part)"),
    SAINT_PIERRE_AND_MIQUELON("Saint Pierre and Miquelon"),
    SAINT_VINCENT_AND_GRENADINES("Saint Vincent and Grenadines"),
    SAMOA("Samoa"),
    SAN_MARINO("San Marino"),
    SAN_MARTIN("Saint-Martin (French Part)"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe"),
    SAUDI_ARABIA("Saudi Arabia"),
    SENEGAL("Senegal"),
    SERBIA("Serbia"),
    SEYCHELLES("Seychelles"),
    SINGAPORE("Singapore"),
    SIERRA_LEONE("Sierra Leone"),
    SLOVAKIA("Slovakia"),
    SLOVENIA("Slovenia"),
    SOLOMON_ISLANDS("Solomon Islands"),
    SOMALIA("Somalia"),
    SOUTH_AFRICA("South Africa"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("South Georgia and the South Sandwich Islands"),
    SOUTH_KOREA("South Korea"),
    SOUTH_SUDAN("South Sudan"),
    SPAIN("Spain"),
    SRI_LANKA("Sri Lanka"),
    SUDAN("Sudan"),
    SURINAME("Suriname"),
    SWAZILAND("Swaziland"),
    SWEDEN("Sweden"),
    SWITZERLAND("Switzerland"),
    SVALBARD_AND_JAN_MAYEN_ISLANDS("Svalbard and Jan Mayen Islands"),
    SYRIAN_ARAB_REPUBLIC("Syrian Arab Republic (Syria)"),
    TAIWAN_REPUBLIC_OF_CHINA("Taiwan, Republic of China"), // controversial, but this is what the API uses
    TAJIKISTAN("TAJIKISTAN"),
    TANZANIA("Tanzania, United Republic of"),
    THAILAND("Thailand"),
    TIMOR_LESTE("Timor Leste"),
    TOGO("Togo"),
    TOKELAU("Tokelau"),
    TONGA("Tonga"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago"),
    TUNISIA("Tunisia"),
    TURKMENISTAN("Turkmenistan"),
    TURKEY("Turkey"),
    TURKS_AND_CAICOS_ISLANDS("Turks and Caicos Islands"),
    TUVALU("Tuvalu"),
    UGANDA("Uganda"),
    UKRAINE("Ukraine"),
    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    UNITED_KINGDOM("United Kingdom"),
    UNITED_STATES_OF_AMERICA("United States of America"),
    URUGUAY("Uruguay"),
    US_MINOR_OUTLYING_ISLANDS("US Minor Outlying Islands"),
    UZBEKISTAN("Uzbekistan"),
    VANUATU("Vanuatu"),
    VENEZUELA("Venezuela (Bolivarian Republic)"),
    VIET_NAM("Vietnam"),
    VIRGIN_ISLANDS("Virgin Islands, US"),
    WALLIS_AND_FUTUNA_ISLANDS("Wallis and Futuna Islands"),
    WESTERN_SAHARA("Western Sahara"),
    YEMEN("Yemen"),
    ZAMBIA("Zambia"),
    ZIMBABWE("Zimbabwe");

    private String countryName;

    CountryName(String countryName) {
        this.countryName = countryName;
    }
}
