package com.karankumar.covid19dashboard.backend;

// This should be kept in alphabetical order
// The country names and slug names should match https://api.covid19api.com/countries
// With the exception of Vietnam (the API made a mistake)
public enum CountryName {
    AFGHANISTAN("afghanistan", "Afghanistan"),
    ALA_ALAND_ISLANDS("ala-aland-islands", "ALA Aland Islands"),
    ALBANIA("albania", "Albania"),
    ALGERIA("algeria", "Algeria"),
    AMERICAN_SAMOA("american-samoa", "American Samoa"),
    ANDORRA("andorra", "Andorra"),
    ANGOLA("angola", "Angola"),
    ANGUILLA("anguilla", "Anguilla"),
    ANTARCTICA("antarctica", "Antarctica"),
    ANTIGUA("antigua-and-barbuda", "Antigua and Barbuda"),
    ARGENTINA("argentina", "Argentina"),
    ARMENIA("armenia", "Armenia"),
    AUSTRALIA("australia", "Australia"),
    AUSTRIA("austria", "Austria"),
    ARUBA("aruba", "Aruba"),
    AZERBAIJAN("azerbaijan", "Azerbaijan"),
    BAHAMAS("bahamas", "Bahamas"),
    BAHRAIN("bahrain", "Bahrain"),
    BANGLADESH("bangladesh", "Bangladesh"),
    BARBADOS("barbados", "Barbados"),
    BELARUS("belarus", "Belarus"),
    BELGIUM("belgium", "Belgium"),
    BELIZE("belize", "Belize"),
    BENIN("benin", "Benin"),
    BERMUDA("bermuda", "Bermuda"),
    BHUTAN("bhutan", "Bhutan"),
    BOLIVIA("bolivia", "Bolivia"),
    BOSNIA_AND_HERZEGOVINA("bosnia-and-herzegovina", "Bosnia and Herzegovina"),
    BOTSWANA("botswana", "Botswana"),
    BOUVET_ISLAND("bouvet-island", "Bouvet Island"),
    BRAZIL("brazil", "Brazil"),
    BRITISH_INDIAN_OCEAN_TERRITORY("british-indian-ocean-territory", "British Indian Ocean Territory"),
    BRITISH_VIRGIN_ISLANDS("british-virgin-islands", "British Virgin Islands"),
    BRUNEI_DARUSSALAM("brunei", "Brunei"),
    BULGARIA("bulgaria", "Bulgaria"),
    BURKINA_FASO("burkina-faso", "Burkina Faso"),
    BURUNDI("burundi", "Burundi"),
    CAMBODIA("cambodia", "Cambodia"),
    CAMEROON("cameroon", "Cameroon"),
    CANADA("canada", "Canada"),
    CAPE_VERDE("cape-verde", "Cape Verde"),
    CAYMAN_ISLANDS("cayman-islands", "Cayman Islands"),
    CENTRAL_AFRICAN_REPUBLIC("central-african-republic", "Central African Republic"),
    CHAD("chad", "Chad"),
    CHILE("chile", "Chile"),
    CHINA("china", "China"),
    CHRISTMAS_ISLAND("christmas-island", "Christmas Island"),
    COCOS_KEELING_ISLANDS("cocos-keeling-islands", "Cocos (Keeling) Islands"),
    COOK_ISLANDS("cook-islands", "Cook Islands"),
    COLOMBIA("colombia", "Colombia"),
    COMOROS("comoros", "Comoros"),
    CONGO_BRAZZAVILLE("congo_brazzaville", "Congo (Brazzaville)"),
    CONGO_KINSHASA("congo-kinshasa", "Congo (Kinshasa)"),
    COSTA_RICA("costa-rica", "Costa Rica"),
    CÔTE_D_IVOIRE("cote-divoire", "Côte d'Ivoire"),
    CROATIA("croatia", "Croatia"),
    CUBA("cuba", "Cuba"),
    CYPRUS("cyprus", "Cyprus"),
    CZECH_REPUBLIC("czech-republic", "Czech Republic"),
    DENMARK("denmark", "Denmark"),
    DJIBOUTI("djibouti", "Djibouti"),
    DOMINICA("dominica", "Dominica"),
    DOMINICAN_REPUBLIC("dominican-republic", "Dominican Republic"),
    ECUADOR("ecuador", "Ecuador"),
    EGYPT("egypt", "Egypt"),
    EL_SALVADOR("el-salvador", "El Salvador"),
    EQUATORIAL_GUINEA("equatorial-guinea", "Equatorial Guinea"),
    ERITREA("eritrea", "Eritrea"),
    ESTONIA("estonia", "Estonia"),
    ETHIOPIA("ethiopia", "Ethiopia"),
    FALKLAND_ISLANDS_MALVINAS("falkland-islands-malvinas", "Falkland Islands (Malvinas)"),
    FAROE_ISLANDS("faroe-islands", "Faroe Islands"),
    FIJI("fiji", "Fiji"),
    FINLAND("finland", "Finland"),
    FRANCE("france", "France"),
    FRENCH_GUIANA("french-guiana", "French Guiana"),
    FRENCH_POLYNESIA("french-polynesia", "French Polynesia"),
    FRENCH_SOUTHERN_TERRITORIES("french-southern-territories", "French Southern Territories"),
    GABON("gabon", "Gabon"),
    GAMBIA("gambia", "Gambia"),
    GEORGIA("georgia", "Georgia"),
    GERMANY("germany", "Germany"),
    GHANA("ghana", "Ghana"),
    GIBRALTAR("gibraltar", "Gibraltar"),
    GREECE("greece", "Greece"),
    GREENLAND("greenland", "Greenland"),
    GRENADA("grenada", "Grenada"),
    GUADELOUPE("guadeloupe", "Guadeloupe"),
    GUAM("guam", "Guam"),
    GUATEMALA("guatemala", "Guatemala"),
    GUERNSEY("guernsey", "Guernsey"),
    GUINEA("guinea", "Guinea"),
    GUINEA_BISSAU("guinea-bissau", "Guinea-Bissau"),
    GUYANA("guyana", "Guyana"),
    HAITI("haiti", "Haiti"),
    HEARD_AND_MCDONALD_ISLANDS("heard-and-mcdonald-islands", "Heard and Mcdonald Islands"),
    HOLY_SEE("holy-see-vatican-city-state", "Holy See (Vatican City State)"),
    HONDURAS("honduras", "Honduras"),
    HONG_KONG("hong-kong-sar-china", "Hong Kong"),
    HUNGARY("hungary", "Hungary"),
    ICELAND("iceland", "Iceland"),
    INDONESIA("indonesia", "Indonesia"),
    INDIA("india", "India"),
    IRAQ("iraq", "Iraq"),
    IRAN("iran", "Iran, Islamic Republic of"),
    IRELAND("ireland", "Ireland"),
    ISLE_OF_MAN("isle-of-man", "Isle of Man"),
    ISRAEL("israel", "Israel"),
    ITALY("italy", "Italy"),
    JAMAICA("jamaica", "Jamaica"),
    JAPAN("japan", "Japan"),
    JERSEY("jersey", "Jersey"),
    JORDAN("jordan", "Jordan"),
    KAZAKHSTAN("kazakhstan", "Kazakhstan"),
    KENYA("kenya", "Kenya"),
    KIRIBATI("kiribati", "Kiribati"),
    KOREA_NORTH("korea-north", "Korea (North)"),
    KOREA_SOUTH("korea-south", "Korea (South)"),
    KUWAIT("kuwait", "Kuwait"),
    KYRGYZSTAN("kyrgyzstan", "Kyrgyzstan"),
    LAO_PDR("lao-pdr", "Lao PDR"),
    LATVIA("latvia", "Latvia"),
    LEBANON("lebanon", "Lebanon"),
    LESOTHO("lesotho", "Lesotho"),
    LIBERIA("liberia", "Liberia"),
    LIBYA("libya", "Libya"),
    LIECHTENSTEIN("liechtenstein", "Liechtenstein"),
    LITHUANIA("lithuania", "Lithuania"),
    LUXEMBOURG("luxembourg", "Luxembourg"),
    MACAO("macao-sar-china", "Macao, SAR China"),
    MACEDONIA("macedonia", "Macedonia"),
    MADAGASCAR("madagascar", "Madagascar"),
    MALAWI("malawi", "Malawi"),
    MALAYSIA("malaysia", "Malaysia"),
    MALDIVES("maldives", "Maldives"),
    MALI("mali", "Mali"),
    MALTA("malta", "Malta"),
    MARSHALL_ISLANDS("marshall-islands", "Marshall Islands"),
    MARTINIQUE("martinique", "Martinique"),
    MAURITANIA("mauritania", "Mauritania"),
    MAURITIUS("mauritius", "Mauritius"),
    MAYOTTE("mayotte", "Mayotte"),
    MEXICO("mexico", "Mexico"),
    MICRONESIA("micronesia", "Micronesia, Federated States of"),
    MOLDOVA("moldova", "Moldova"),
    MONACO("monaco", "Monaco"),
    MONGOLIA("mongolia", "Mongolia"),
    MONTENEGRO("montenegro", "Montenegro"),
    MONTSERRAT("montserrat", "Montserrat"),
    MOROCCO("morocco", "Morocco"),
    MOZAMBIQUE("mozambique", "Mozambique"),
    MYANMAR("myanmar", "Myanmar"),
    NAMIBIA("namibia", "Namibia"),
    NAURU("nauru", "Nauru"),
    NEPAL("nepal", "Nepal"),
    NETHERLANDS("netherlands", "Netherlands"),
    NETHERLANDS_ANTILLES("netherlands-antilles", "Netherlands Antilles"),
    NEW_CALEDONIA("new-caledonia", "New Caledonia"),
    NEW_ZEALAND("new-zealand", "New Zealand"),
    NICARAGUA("nicaragua", "Nicaragua"),
    NIGER("niger", "Niger"),
    NIGERIA("nigeria", "Nigeria"),
    NIUE("niue", "Nieu"),
    NORFOLK_ISLAND("norfolk-island", "Norfolk Island"),
    NORTHERN_MARIANA_ISLANDS("northern-Mariana-islands", "Northern Mariana Islands"),
    NORWAY("norway", "Norway"),
    OMAN("oman", "Oman"),
    PALAU("palau", "Palau"),
    PALESTINIAN_TERRITORY("palestine", "Palestinian Territory"),
    PAKISTAN("pakistan", "Pakistan"),
    PANAMA("panama", "Panama"),
    PAPUA_NEW_GUINEA("papua-new-guinea", "Papua New Guinea"),
    PARAGUAY("paraguay", "Paraguay"),
    PERU("peru", "Peru"),
    PHILIPPINES("philippines", "Philippines"),
    PITCAIRN("pitcairn", "Pitcairn"),
    POLAND("poland", "Poland"),
    PUERTO_RICO("puerto-rico", "Puerto Rico"),
    PORTUGAL("portugal", "Portugal"),
    QATAR("qatar", "Qatar"),
    REPUBLIC_OF_KOSOVO("kosovo", "Republic of Kosovo"),
    RUSSIAN_FEDERATION("russia", "Russian Federation"),
    RÉUNION("réunion", "Réunion"),
    ROMANIA("romania", "Romania"),
    RWANDA("rwanda", "Rwanda"),
    SAINT_BARTHÉLEMY("saint-barthélemy", "Saint-Barthélemy"),
    SAINT_HELENA("saint-helena", "Saint Helena"),
    SAINT_KITTS_AND_NEVIS("saint-kitts-and-nevis", "Saint Kitts and Nevis"),
    SAINT_LUCIA("saint-lucia", "Saint Lucia"),
    SAINT_MARTIN_FRENCH_PART("saint-martin-french-part", "Saint-Martin (French Part)"),
    SAINT_PIERRE_AND_MIQUELON("saint-pierre-and-miquelon", "Saint Pierre and Miquelon"),
    SAINT_VINCENT_AND_GRENADINES("saint-vincent-and-the-grenadines", "Saint Vincent and Grenadines"),
    SAMOA("samoa", "Samoa"),
    SAN_MARINO("san-marino", "San Marino"),
    SAO_TOME_AND_PRINCIPE("sao-tome-and-principe", "Sao Tome and Principe"),
    SAUDI_ARABIA("saudi-arabia", "Saudi Arabia"),
    SENEGAL("senegal", "Sengal"),
    SERBIA("serbia", "Serbia"),
    SEYCHELLES("seychelles", "Seychelles"),
    SINGAPORE("singapore", "Singapore"),
    SIERRA_LEONE("sierra-leone", "Sierra Leone"),
    SLOVAKIA("slovakia", "Slovakia"),
    SLOVENIA("slovenia", "Slovenia"),
    SOLOMON_ISLANDS("solomon-islands", "Solomon Islands"),
    SOMALIA("somalia", "Somalia"),
    SOUTH_AFRICA("south-africa", "South Africa"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("south-georgia-and-the-south-sandwich-islands",
            "South Georgia and the South Sandwich Islands"),
    SOUTH_SUDAN("south-sudan", "South Sudan"),
    SPAIN("spain", "Spain"),
    SRI_LANKA("sri-lanka", "Sri Lanka"),
    SUDAN("sudan", "Sudan"),
    SURINAME("suriname", "Suriname"),
    SWAZILAND("swaziland", "Swaziland"),
    SWEDEN("sweden", "Sweden"),
    SWITZERLAND("switzerland", "Switzerland"),
    SVALBARD_AND_JAN_MAYEN_ISLANDS("svalbard-and-jan-mayen-islands", "Svalbard and Jan Mayen Islands"),
    SYRIAN_ARAB_REPUBLIC("syria", "Syrian Arab Republic (Syria)"),
    TAIWAN("taiwan", "Taiwan, Republic of China"), // controversial, but this is the name the API uses
    TAJIKISTAN("tajikistan", "Tajikistan"),
    TANZANIA("tanzania", "Tanzania, United Republic of"),
    THAILAND("thailand", "Thailand"),
    TIMOR_LESTE("timor-leste", "Timor-Leste"),
    TOGO("togo", "Togo"),
    TOKELAU("tokelau", "Tokelau"),
    TONGA("tonga", "Tonga"),
    TRINIDAD_AND_TOBAGO("trinidad-and-tobago", "Trinidad and Tobago"),
    TUNISIA("tunisia", "Tunisia"),
    TURKMENISTAN("turkmenistan", "Turkmenistan"),
    TURKEY("turkey", "Turkey"),
    TURKS_AND_CAICOS_ISLANDS("turks-and-caicos-islands", "Turks and Caicos Islands"),
    TUVALU("tuvalu", "Tuvalu"),
    UGANDA("uganda", "Uganda"),
    UKRAINE("ukraine", "Ukraine"),
    UNITED_ARAB_EMIRATES("united-arab-emirates", "United Arab Emirates"),
    UNITED_KINGDOM("united-kingdom", "United Kingdom"),
    UNITED_STATES_OF_AMERICA("united-states", "United States of America"),
    URUGUAY("uruguay", "Uruguay"),
    US_MINOR_OUTLYING_ISLANDS("us-minor-outlying-islands", "US Minor Outlying Islands"),
    UZBEKISTAN("uzbekistan", "Uzbekistan"),
    VANUATU("vanuatu", "Vanuatu"),
    VENEZUELA("venezuela", "Venezuela (Bolivarian Republic)"),
    VIETNAM("vietnam", "Vietnam"),
    VIRGIN_ISLANDS_US("virgin-islands", "Virgin Islands, US"),
    WALLIS_AND_FUTUNA_ISLANDS("wallis-and-futuna-islands", "Wallis and Futuna Islands"),
    WESTERN_SAHARA("western-sahara", "Western Sahara"),
    YEMEN("yemen", "Yemen"),
    ZAMBIA("zambia", "Zambia"),
    ZIMBABWE("zimbabwe", "Zimbabwe");

    private String slug;
    private String countryName;

    CountryName(String slug, String countryName) {
        this.slug = slug;
        this.countryName = countryName;
    }

    public String getSlug(CountryName countryName) {
        return countryName.slug;
    }

    @Override
    public String toString() {
        return countryName;
    }
}
